# Site settings
title:          Tale
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/tale"
url:            "https://chesterhow.github.io"

# Google Analytics
google_analytics: UA-30399492-1

# Baidu Statistic
baidu_statistic: 6e5f92006f4eed18f39b7cb30f420d8a

# Google AdSense
google_adsense: 

# cnzz statistic
cnzz_statistic: 

# addthis
addthis: 

copyright:    'hutusi.com'
# Author
author:
  name:         hutusi
  url:          https://hutusi.com
  email:        huziyong@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jekyll/tagging
  # - jekyll-sitemap
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Navigators
nav_page_names: ['about.md']
# can be ['feeds.pub', 'xml', 'na']
nav_feed: 'feeds.pub'

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Tagging
# tag_page_dir:         tag
# tag_page_layout:      tag_page
# tag_permalink_style:  pretty

# tag_page_data:
#   sitemap: false

# can be ['disqus', 'gitalk', 'giscus']
comments_engine: na

# Disqus (Set to your disqus id)
disqus: jekyll-tale

gitalk:
  client_id: ''
  client_secret: ''
  repo: ''
  owner: ''
  admin: 
    - ''

giscus:
  repo: ''
  repo_id: ''
  category: ''
  category_id: ''
  mapping: 'pathname'
  input_position: 'bottom'
  theme: 'light'
  lang: "en"
